MINT-1815 stop build on lint errors in the master & release branches

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,8 +25,8 @@ jobs:
         - yarn testrpc > /dev/null &
         - yarn contracts
       script:
+        - yarn lint:errors; export LINT_RESULT=$?
         - yarn build --production
-        - yarn lint:errors
       after_script:
         - FULL_GCR_KEY="-----BEGIN PRIVATE KEY-----\n"$GCR_KEY"\n-----END PRIVATE KEY-----\n"
         - sed -i -e "s%\PWD%$FULL_GCR_KEY%g" gcregistry.json
@@ -42,14 +42,20 @@ jobs:
           fi;
         - IMAGE_TAG_NAME="latest"
         - |
-          if [ "$TRAVIS_BRANCH" == "master" ]; then
-            docker build --build-arg BUILD_BRANCH="master" --build-arg PUBLIC_BACKEND_REST_URL="https://backend.chronobank.io" --build-arg NODE=production -t gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME . --no-cache
-            docker push gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME
-          elif [ "$TRAVIS_BRANCH" == "develop" ]; then
+          if [ "$LINT_RESULT" == "0" ]; then
+            if [ "$TRAVIS_BRANCH" == "master" ]; then
+              docker build --build-arg BUILD_BRANCH="master" --build-arg PUBLIC_BACKEND_REST_URL="https://backend.chronobank.io" --build-arg NODE=production -t gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME . --no-cache
+              docker push gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME
+            elif [ "$TRAVIS_BRANCH" == "release" ]; then
+              docker build --build-arg BUILD_BRANCH="release" --build-arg PUBLIC_BACKEND_REST_URL="https://backend.chronobank.io" -t gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME . --no-cache
+              docker push gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME
+            fi;
+          elif [ "$TRAVIS_BRANCH" != "develop" ]; then
+            echo "Lint check is failed with the exit code: $TEST_RESULT. Skipping image build and terminate!"
+          fi;
+        - |
+          if [ "$TRAVIS_BRANCH" == "develop" ]; then
             docker build --build-arg BUILD_BRANCH="develop" --build-arg PUBLIC_BACKEND_REST_URL="https://stage-adm.chronobank.io" -t gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME . --no-cache
-            docker push gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME
-          elif [ "$TRAVIS_BRANCH" == "release" ]; then
-            docker build --build-arg BUILD_BRANCH="release" --build-arg PUBLIC_BACKEND_REST_URL="https://backend.chronobank.io" -t gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME . --no-cache
             docker push gcr.io/deep-wares-144610/$TRAVIS_BRANCH/chronomint:$IMAGE_TAG_NAME
           fi;
         - kill -9 $(ps aux | grep '[t]estrpc' | awk '{print $2}')
